name: Build and test

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Run build
      run: make build
    - name: Run tests
      run: make test
